const citiesMockedData=
     {"CityResource":{
		"Cities":{
            	"City":[{
				"CityCode":"FRA",
				"CountryCode":"DE",
				"Names":{
					"Name":{
						"@LanguageCode":"EN",
						"$":"Frankfurt"
					}	
				},
				"UtcOffset":"+01:00",
				"TimeZoneId":"Europe/Berlin",
				"Airports":{
					"AirportCode":["FRA","FRF","HHN","QGV","ZRB"]
				}
            	},
			{
				"CityCode":"ROM",
				"CountryCode":"IT",
				"Names":{
					"Name":{
						"@LanguageCode":"EN",
						"$":"Rome"
					}
				},
				"UtcOffset":"+01:00",
				"TimeZoneId":"Europe/Berlin",
				"Airports":{
					"AirportCode":["FCO"]
				}
			}]
          },
     }}
export default citiesMockedData;